import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <StoreProvider>
            {/* <Header /> */}
            <div className="flex flex-1 grow"> {children}</div>
            {/* <Footer /> */}
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
